// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeusjdxqevzwogkxthrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhldXNqZHhxZXZ6d29na3h0aHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODk2NDUsImV4cCI6MjA1Nzc2NTY0NX0.66x7sb2nPaqNzdAB1kOLRN5_o5KGISzSZaKvEo2q8ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);